"""Initial migration: create location, building, owner, features, and listing tables

Revision ID: 8c57b2c84100
Revises: 
Create Date: 2025-12-20 15:21:30.550249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c57b2c84100'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('building_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_built', sa.SmallInteger(), nullable=True),
    sa.Column('building_type', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('features',
    sa.Column('features_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('has_basement', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('kitchen_type', sa.String(length=100), nullable=True),
    sa.Column('window_type', sa.String(length=100), nullable=True),
    sa.Column('ownership_type', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('features_id')
    )
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('city_district', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('full_address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('owner',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('listing',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('features_id', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.SmallInteger(), nullable=True),
    sa.Column('area', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price_total_zl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_sqm_zl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_sqm_detailed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.building_id'], ),
    sa.ForeignKeyConstraint(['features_id'], ['features.features_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.owner_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    op.drop_table('owner')
    op.drop_table('location')
    op.drop_table('features')
    op.drop_table('building')
    # ### end Alembic commands ###
